[package]
name = "q3_assignment5"
version = "0.1.0"
authors = ["Alifya Hussain <alifyahussain53@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"